server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: /tmp
      prefix: access_log
      suffix: .log
      pattern: '%h %l %u %t "%r" %s %b %D'

spring:
  application:
    name: gscix-backend
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://elasticsearch:9200}
    
opencti:
  url: ${OPENCTI_URL:http://opencti:8080}
  token: ${OPENCTI_TOKEN:default_token}
